apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployement
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: primesh96/kub-demo-frontend:latest

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          # ports:
          # - containerPort: <Port>
