apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployement
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: primesh96/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          # ports:
          # - containerPort: <Port>
